Add goposts.site domain
wesbos/burner-email-providers pull request #276
Opened 2021-04-09 18:42 UTC by dolfinus

According to https://www.ipqualityscore.com/domain-reputation/goposts.site this is a disposable email site.

2021-04-10 11:48 UTC, emh-rowland-oconnor requested changes
Hi.

Thank you. Can you please provide more information on why this is a disposable email domain?

- The webpage is a holding page
- The MX records and servers do not seem to be suspicious

2021-04-10 13:37 UTC, dolfinus commented
I've got several registrations from this domain for past 3-4 months. All of these emails had a random prefix and registered users have random names too.

If you think that's not enough evidence to add this domain to a list, I'll close this PR.

2021-04-11 09:46 UTC, emh-rowland-oconnor approved these changes

2021-04-11 09:47 UTC, merged

2021-04-11 09:47 UTC, emh-rowland-oconnor commented
Thank you.